// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"seckill-system/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/activity/create",
				Handler: createActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order/status",
				Handler: queryOrderStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/seckill",
				Handler: doSeckillHandler(serverCtx),
			},
		},
	)
}
